name: Download

on:
  push:
    tags:
      - '**'

jobs:
  download-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Pull Docker image
        run: docker pull openjdk:17-oraclelinux7
        
      - name: List Docker images
        run: docker images

      - name: Export Docker image
        run: docker save -o openjdk_x86.tar openjdk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openjdk_x86.tar
          path: openjdk_x86.tar
